#pragma once

#define FRAME_BUFFER_WIDTH	800
#define FRAME_BUFFER_HEIGHT	600

// 프레임 버퍼의 크기와 종횡비(Aspect Ratio)를 나타내는 상수를 다음과 같이 선언한다. 
#define ASPECT_RATIO (float(FRAME_BUFFER_WIDTH) / float(FRAME_BUFFER_HEIGHT))

/*정점의 색상을 무작위로(Random) 설정하기 위해 사용한다. 각 정점의 색상은 난수(Random Number)를 생성하여
지정한다.*/
#define RANDOM_COLOR XMFLOAT4(rand() / float(RAND_MAX), rand() / float(RAND_MAX), rand() / float(RAND_MAX), rand() / float(RAND_MAX))


#define UI_MAIN_SIGLESETTING_BUTTON_WIDTH	300
#define UI_MAIN_SIGLESETTING_BUTTON_HEIGHT	100
#define UI_MAIN_SIGLESETTING_BUTTON_x		0.f
#define UI_MAIN_SIGLESETTING_BUTTON_y		0.f

#define UI_MAIN_MULTISETTING_BUTTON_WIDTH	300
#define UI_MAIN_MULTISETTING_BUTTON_HEIGHT	100
#define UI_MAIN_MULTISETTING_BUTTON_x		0.f
#define UI_MAIN_MULTISETTING_BUTTON_y		-150.0f

#define UI_SINGLE_START_BUTTON_WIDTH		300
#define UI_SINGLE_START_BUTTON_HEIGHT		100
#define UI_SINGLE_START_BUTTON_x			0.f
#define UI_SINGLE_START_BUTTON_y			-FRAME_BUFFER_HEIGHT/2 + UI_SINGLE_START_BUTTON_HEIGHT/2

#define UI_MULTI_MULTISETTING_INTERFACE_1_WIDTH		200
#define UI_MULTI_MULTISETTING_INTERFACE_1_HEIGHT	400
#define UI_MULTI_MULTISETTING_INTERFACE_1_x			-FRAME_BUFFER_WIDTH/2 + UI_MULTI_MULTISETTING_INTERFACE_1_WIDTH/2
#define UI_MULTI_MULTISETTING_INTERFACE_1_y			FRAME_BUFFER_HEIGHT/2 - UI_MULTI_MULTISETTING_INTERFACE_1_HEIGHT/2

#define UI_MULTI_MULTISETTING_INTERFACE_2_WIDTH		200
#define UI_MULTI_MULTISETTING_INTERFACE_2_HEIGHT	400
#define UI_MULTI_MULTISETTING_INTERFACE_2_x			FRAME_BUFFER_WIDTH/2 - UI_MULTI_MULTISETTING_INTERFACE_2_WIDTH/2
#define UI_MULTI_MULTISETTING_INTERFACE_2_y			FRAME_BUFFER_HEIGHT/2 - UI_MULTI_MULTISETTING_INTERFACE_2_HEIGHT/2

#define UI_MULTI_START_BUTTON_WIDTH		300
#define UI_MULTI_START_BUTTON_HEIGHT	100
#define UI_MULTI_START_BUTTON_x			0.f
#define UI_MULTI_START_BUTTON_y			-FRAME_BUFFER_HEIGHT/2 + UI_MULTI_START_BUTTON_HEIGHT/2