#pragma once

#define FRAME_BUFFER_WIDTH	800
#define FRAME_BUFFER_HEIGHT	600

// 프레임 버퍼의 크기와 종횡비(Aspect Ratio)를 나타내는 상수를 다음과 같이 선언한다. 
#define ASPECT_RATIO (float(FRAME_BUFFER_WIDTH) / float(FRAME_BUFFER_HEIGHT))

/*정점의 색상을 무작위로(Random) 설정하기 위해 사용한다. 각 정점의 색상은 난수(Random Number)를 생성하여
지정한다.*/
#define RANDOM_COLOR XMFLOAT4(rand() / float(RAND_MAX), rand() / float(RAND_MAX), rand() / float(RAND_MAX), rand() / float(RAND_MAX))

// 메인 메뉴 - 싱글플레이 버튼
#define UI_MAIN_SIGLESETTING_BUTTON_WIDTH	300
#define UI_MAIN_SIGLESETTING_BUTTON_HEIGHT	100
#define UI_MAIN_SIGLESETTING_BUTTON_x		0.f
#define UI_MAIN_SIGLESETTING_BUTTON_y		0.f
// 메인 메뉴 - 멀티플레이 버튼
#define UI_MAIN_MULTISETTING_BUTTON_WIDTH	300
#define UI_MAIN_MULTISETTING_BUTTON_HEIGHT	100
#define UI_MAIN_MULTISETTING_BUTTON_x		0.f
#define UI_MAIN_MULTISETTING_BUTTON_y		-150.0f
// 싱글플레이 - 스타트 버튼
#define UI_SINGLE_START_BUTTON_WIDTH		300
#define UI_SINGLE_START_BUTTON_HEIGHT		100
#define UI_SINGLE_START_BUTTON_x			0.f
#define UI_SINGLE_START_BUTTON_y			-FRAME_BUFFER_HEIGHT/2 + UI_SINGLE_START_BUTTON_HEIGHT/2
// 멀티플레이 - 무기선택 인터페이스
#define UI_MULTI_MULTISETTING_INTERFACE_1_WIDTH		200
#define UI_MULTI_MULTISETTING_INTERFACE_1_HEIGHT	400
#define UI_MULTI_MULTISETTING_INTERFACE_1_x			-FRAME_BUFFER_WIDTH/2 + UI_MULTI_MULTISETTING_INTERFACE_1_WIDTH/2
#define UI_MULTI_MULTISETTING_INTERFACE_1_y			FRAME_BUFFER_HEIGHT/2 - UI_MULTI_MULTISETTING_INTERFACE_1_HEIGHT/2
// 멀티플레이 - 방패선택 인터페이스
#define UI_MULTI_MULTISETTING_INTERFACE_2_WIDTH		200
#define UI_MULTI_MULTISETTING_INTERFACE_2_HEIGHT	400
#define UI_MULTI_MULTISETTING_INTERFACE_2_x			FRAME_BUFFER_WIDTH/2 - UI_MULTI_MULTISETTING_INTERFACE_2_WIDTH/2
#define UI_MULTI_MULTISETTING_INTERFACE_2_y			FRAME_BUFFER_HEIGHT/2 - UI_MULTI_MULTISETTING_INTERFACE_2_HEIGHT/2
// 멀티플레이 - 스타트 버튼
#define UI_MULTI_START_BUTTON_WIDTH		300
#define UI_MULTI_START_BUTTON_HEIGHT	100
#define UI_MULTI_START_BUTTON_x			0.f
#define UI_MULTI_START_BUTTON_y			-FRAME_BUFFER_HEIGHT/2 + UI_MULTI_START_BUTTON_HEIGHT/2

// 텍스쳐 관련
#define RESOURCE_TEXTURE2D			0x01
#define RESOURCE_TEXTURE2D_ARRAY	0x02	//[]
#define RESOURCE_TEXTURE2DARRAY		0x03
#define RESOURCE_TEXTURE_CUBE		0x04
#define RESOURCE_BUFFER				0x05

#define _WITH_BATCH_MATERIAL

#define TEXTURES				6

// 플레이어 방향
#define DIR_FORWARD 0x01
#define DIR_BACKWARD 0x02
#define DIR_LEFT 0x04
#define DIR_RIGHT 0x08
#define DIR_UP 0x10
#define DIR_DOWN 0x20

// 씬의 상태
enum class SceneState {
	MAIN_MENU,
	SINGLE_SETTING,
	SINGLE_PLAY,
	MULTI_SETTING,
	MULTI_PLAY,
};
